Repository ciromattia/kcc, pull requests merged in 2024-05, with the labels that each got.

#691 Kindle Scribe 1860 max width
  kindlecomicconverter/comic2ebook.py
  kindlecomicconverter/image.py
Labels: Kindle

#693 reduce dependency on 7z, unar, homebrew by using builtin tar
  kindlecomicconverter/KCC_gui.py
  kindlecomicconverter/comic2ebook.py
  kindlecomicconverter/comicarchive.py
Labels: dependencies

#561 Add de-dupe cover option for landscape alignment
  gui/KCC.ui
  kindlecomicconverter/KCC_gui.py
  kindlecomicconverter/KCC_rc.py
  kindlecomicconverter/KCC_ui.py
  kindlecomicconverter/KCC_ui_editor.py
  kindlecomicconverter/comic2ebook.py
Labels: Enhancement
